### ISSUE TITLE
Add custom CA path for certificate validation

### ISSUE THREAD

**Issue by lucaCigarini** [zabbix/python-zabbix-utils#16]
Hello,

[Zabbix API](https://github.com/zabbix/python-zabbix-utils/blob/d4f254abb9356fafc719e76a0040da73d78b5308/zabbix_utils/api.py#L119) class allows a developer to enforce certificate validation through `validate_certs` parameter.

However, it's not clear where CAs will be found. Furthermore, there's no way of specifying a custom path to a CA like requests do with verify parameter.

Could it be possible to add a way to provide a path to a custom CA?

Thank you!

**Comment by aiantsen** [comment]
Hi @lucaCigarini, thank you for your suggestion and your attention to the library. 

A way to provide a custom CA and other certificate related settings has been implemented in [v2.0.1](https://github.com/zabbix/python-zabbix-utils/releases/tag/v2.0.1).

Please take a look at a new library version. We hope it will be usefull for your and other library users.
