### ISSUE TITLE
The triggers.get API call always returns all triggers regardless of the host and hostids parameters.

### ISSUE THREAD

**Issue by juanca-nubiral** [zabbix/python-zabbix-utils#17]
When making the triggers.get API call and passing a host or hostids as parameters, it returns all triggers configured in Zabbix instead of filtering those that belong to the specified host. When testing the same method through Postman, it works correctly and only returns the triggers for the host provided as a parameter.

Attached are scripts to reproduce the error.
Python
from zabbix_utils import ZabbixAPI

zabbix_url = "xxxxxxxxxxxxxx"
api_key = "xxxxxxxxxxxxxxxx"
zapi = ZabbixAPI(url=zabbix_url, token=api_key)
hostname= "xxxxxxxxxxx"
hosts = zapi.host.get({"filter": {"host": hostname}})
host_id = hosts[0]['hostid']
triggers = zapi.trigger.get({
        "host": hostname,
        "output": "extend",
    })
for trigger in triggers:
    print(f"- {trigger['description']}")

Postman:
Get: https://xxxxxxxxxxxxxx/api_jsonrpc.php
{
    "jsonrpc": "2.0",
    "method": "trigger.get",
    "params": {
        "host": "xxxxxxxxxxxx",
        "output": "extend"
    },
    "auth": "xxxxxxxxxxxxxxx",
    "id": 1
}

This was tested with Zabbix 7.

**Comment by aiantsen** [comment]
Hello @juanca-nubiral, thanks for your question.

I tried to reproduce your problem and found that you made a mistake in specifying the API request parameters. 
For example, the following code fragment:
```python
triggers = zapi.trigger.get({
    "host": hostname,
    "output": "extend",
})
```
should have been like this instead:
```python
triggers = zapi.trigger.get(
    host = hostname,
    output = "extend"
)
```
or like this:
```python
triggers = zapi.trigger.get(**{
    "host": hostname,
    "output": "extend",
})
```
So, all API methods in the library take as input not a dictionary, but a list of parameters and their values.
Hope this helps you solve your problem.
