### ISSUE TITLE
Add .github directory to gitignore file

### ISSUE THREAD

**Issue by cbbaaron** [zabbix/python-zabbix-utils#6]
Not sure if this was a mistake or not, but it appears your .github directory has also been uploaded to this repository

**Comment by aiantsen** [comment]
Hello @cbbaaron, thanks a lot for your attention!
The point is that `.github` directory is a part of the project and consists GitHub workflows and related files. They can't be ignored by adding to `.gitignore`. I would say it's expected behavior. 
Anyway, thank you for letting us know about it.
